/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinationsystem;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ljk99
 */
public class DoctorLoadingPage extends javax.swing.JFrame {

    private static Doctor currentUser;
    private Hashtable<String, Object> htAppointment;

    /**
     * Creates new form DoctorLoadingPage
     */
    public DoctorLoadingPage() {
        initComponents();
        editProfile(false);

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();

        this.setSize(d);
        this.setMaximumSize(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        lblWbUsername = new javax.swing.JLabel();
        lblVSName2 = new javax.swing.JLabel();
        lblVSName3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        txtAdPNo = new javax.swing.JTextField();
        jDob = new com.toedter.calendar.JDateChooser();
        cboAdPGender = new javax.swing.JComboBox<>();
        calAdPHiredDate = new com.toedter.calendar.JDateChooser();
        txtAdPRole = new javax.swing.JTextField();
        txtAdPUser = new javax.swing.JTextField();
        pnlCredential = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txtPEmail = new javax.swing.JTextField();
        txtPNewPw = new javax.swing.JPasswordField();
        txtPCfmPw = new javax.swing.JPasswordField();
        jLabel99 = new javax.swing.JLabel();
        lblPwNoMatch = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        btnAdPSave = new javax.swing.JButton();
        btnAdPInfoEdit = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        txtAdPFullName = new javax.swing.JTextField();
        jLabel89 = new javax.swing.JLabel();
        txtAdPVacCentre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTA = new javax.swing.JTable();
        txtTaSearch = new javax.swing.JTextField();
        btnTASearch = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTaVaccine = new javax.swing.JTextField();
        txtTaNat = new javax.swing.JTextField();
        txtTaIC = new javax.swing.JTextField();
        txtTaGender = new javax.swing.JTextField();
        txtTaName = new javax.swing.JTextField();
        btnTaMark = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTaCentre = new javax.swing.JTextField();
        txtTaAppCode = new javax.swing.JTextField();
        calTaDob = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTaStatus = new javax.swing.JTextField();
        calTaDate = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        txtTaDose = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTaRemarks = new javax.swing.JTextField();
        cboTaVaccine = new javax.swing.JComboBox<>();
        cboTaStatus = new javax.swing.JComboBox<>();
        cboTaNationality = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinationsystem/covid-19.png"))); // NOI18N

        btnLogout.setBackground(new java.awt.Color(51, 51, 51));
        btnLogout.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.setOpaque(true);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jPanel16.setBackground(new java.awt.Color(102, 0, 0));

        lblWbUsername.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        lblWbUsername.setForeground(new java.awt.Color(0, 0, 0));
        lblWbUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWbUsername.setText("Username");

        lblVSName2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        lblVSName2.setForeground(new java.awt.Color(0, 0, 0));
        lblVSName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVSName2.setText("Doctor Panel");

        lblVSName3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        lblVSName3.setForeground(new java.awt.Color(0, 0, 0));
        lblVSName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVSName3.setText("Welcome Back");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblWbUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblVSName2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
            .addComponent(lblVSName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblVSName3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(lblVSName2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel58.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel58.setText("Committee Code");

        jLabel59.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("User Profile");

        jLabel78.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel78.setText("Role");

        jLabel88.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 255, 255));
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel88.setText("Hired Date");

        jLabel52.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel52.setText("Gender:");

        jLabel54.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel54.setText("Date of Birth:");

        jLabel56.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel56.setText("Contact No:");

        txtAdPNo.setEditable(false);
        txtAdPNo.setBackground(new java.awt.Color(204, 204, 204));
        txtAdPNo.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtAdPNo.setForeground(new java.awt.Color(0, 0, 0));
        txtAdPNo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAdPNo.setEnabled(false);

        jDob.setBackground(new java.awt.Color(255, 255, 255));
        jDob.setForeground(new java.awt.Color(0, 0, 0));
        jDob.setEnabled(false);

        cboAdPGender.setBackground(new java.awt.Color(204, 204, 204));
        cboAdPGender.setForeground(new java.awt.Color(0, 0, 0));
        cboAdPGender.setMaximumRowCount(2);
        cboAdPGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Male", "Female" }));
        cboAdPGender.setEnabled(false);
        cboAdPGender.setOpaque(true);

        calAdPHiredDate.setBackground(new java.awt.Color(255, 255, 255));
        calAdPHiredDate.setForeground(new java.awt.Color(0, 0, 0));
        calAdPHiredDate.setEnabled(false);

        txtAdPRole.setEditable(false);
        txtAdPRole.setBackground(new java.awt.Color(204, 204, 204));
        txtAdPRole.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtAdPRole.setForeground(new java.awt.Color(0, 0, 0));
        txtAdPRole.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAdPRole.setEnabled(false);

        txtAdPUser.setEditable(false);
        txtAdPUser.setBackground(new java.awt.Color(204, 204, 204));
        txtAdPUser.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtAdPUser.setForeground(new java.awt.Color(0, 0, 0));
        txtAdPUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAdPUser.setEnabled(false);

        pnlCredential.setBackground(new java.awt.Color(57, 57, 57));

        jLabel53.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel53.setText("Email:");

        jLabel55.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel55.setText("New Password:");

        txtPEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtPEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtPEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtPEmail.setSelectionColor(new java.awt.Color(255, 255, 51));

        txtPNewPw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPNewPwKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPNewPwKeyTyped(evt);
            }
        });

        txtPCfmPw.setEnabled(false);
        txtPCfmPw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPCfmPwKeyReleased(evt);
            }
        });

        jLabel99.setFont(new java.awt.Font("Bell MT", 0, 10)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(204, 204, 204));
        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel99.setText("Leave this field blank to retain current password.");

        lblPwNoMatch.setFont(new java.awt.Font("Bell MT", 0, 10)); // NOI18N
        lblPwNoMatch.setForeground(new java.awt.Color(204, 0, 0));
        lblPwNoMatch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPwNoMatch.setText("Password doesn't match!");

        jLabel151.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel151.setForeground(new java.awt.Color(255, 255, 255));
        jLabel151.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel151.setText("Confirm Password:");

        javax.swing.GroupLayout pnlCredentialLayout = new javax.swing.GroupLayout(pnlCredential);
        pnlCredential.setLayout(pnlCredentialLayout);
        pnlCredentialLayout.setHorizontalGroup(
            pnlCredentialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCredentialLayout.createSequentialGroup()
                .addGroup(pnlCredentialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCredentialLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(pnlCredentialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCredentialLayout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jLabel151, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                .addGroup(pnlCredentialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPwNoMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCredentialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPCfmPw)
                        .addComponent(txtPNewPw, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtPEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(2445, Short.MAX_VALUE))
        );
        pnlCredentialLayout.setVerticalGroup(
            pnlCredentialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCredentialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCredentialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCredentialLayout.createSequentialGroup()
                        .addComponent(txtPEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPNewPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel99)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCredentialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPCfmPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel151))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPwNoMatch))
                    .addGroup(pnlCredentialLayout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel55)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        btnAdPSave.setBackground(new java.awt.Color(51, 102, 255));
        btnAdPSave.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnAdPSave.setForeground(new java.awt.Color(0, 0, 0));
        btnAdPSave.setText("Save");
        btnAdPSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdPSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdPSave.setOpaque(true);
        btnAdPSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdPSaveActionPerformed(evt);
            }
        });

        btnAdPInfoEdit.setBackground(new java.awt.Color(102, 255, 102));
        btnAdPInfoEdit.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnAdPInfoEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnAdPInfoEdit.setText("Edit Profile");
        btnAdPInfoEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdPInfoEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdPInfoEdit.setOpaque(true);
        btnAdPInfoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdPInfoEditActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel57.setText("Full Name:");

        txtAdPFullName.setEditable(false);
        txtAdPFullName.setBackground(new java.awt.Color(204, 204, 204));
        txtAdPFullName.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtAdPFullName.setForeground(new java.awt.Color(0, 0, 0));
        txtAdPFullName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAdPFullName.setEnabled(false);

        jLabel89.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(255, 255, 255));
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel89.setText("Vaccine Centre:");

        txtAdPVacCentre.setEditable(false);
        txtAdPVacCentre.setBackground(new java.awt.Color(204, 204, 204));
        txtAdPVacCentre.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtAdPVacCentre.setForeground(new java.awt.Color(0, 0, 0));
        txtAdPVacCentre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAdPVacCentre.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(658, 658, 658))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtAdPUser, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAdPRole, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(122, 122, 122)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAdPFullName)
                                            .addComponent(calAdPHiredDate, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAdPVacCentre)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(381, 381, 381)
                                .addComponent(btnAdPSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdPInfoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlCredential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                                    .addComponent(cboAdPGender, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(123, 123, 123)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAdPNo, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)))
                                .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(txtAdPUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78)
                    .addComponent(txtAdPRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel88)
                    .addComponent(calAdPHiredDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel89)
                    .addComponent(txtAdPVacCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(txtAdPFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(cboAdPGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel54)
                    .addComponent(jDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(txtAdPNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(pnlCredential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdPInfoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdPSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel4);

        jTabbedPane1.addTab("Profile", jScrollPane4);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setAutoscrolls(true);

        jPanel18.setBackground(new java.awt.Color(51, 51, 51));

        tblTA.setBackground(new java.awt.Color(255, 255, 255));
        tblTA.setForeground(new java.awt.Color(0, 0, 0));
        tblTA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Username", "Full Name", "IC/Passport", "Vaccine", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTA.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTA);

        txtTaSearch.setBackground(new java.awt.Color(255, 255, 255));
        txtTaSearch.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtTaSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtTaSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTaSearch.setSelectionColor(new java.awt.Color(255, 255, 51));

        btnTASearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinationsystem/search.png"))); // NOI18N
        btnTASearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTASearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTASearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTASearchActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(51, 153, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(518, 500));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Full Name:");

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Gender:");

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("IC/Passport:");

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Date");

        txtTaVaccine.setEditable(false);
        txtTaVaccine.setBackground(new java.awt.Color(204, 204, 204));
        txtTaVaccine.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTaVaccine.setForeground(new java.awt.Color(0, 0, 0));
        txtTaVaccine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaVaccine.setSelectionColor(new java.awt.Color(255, 255, 51));

        txtTaNat.setEditable(false);
        txtTaNat.setBackground(new java.awt.Color(204, 204, 204));
        txtTaNat.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTaNat.setForeground(new java.awt.Color(0, 0, 0));
        txtTaNat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaNat.setSelectionColor(new java.awt.Color(255, 255, 51));

        txtTaIC.setEditable(false);
        txtTaIC.setBackground(new java.awt.Color(204, 204, 204));
        txtTaIC.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTaIC.setForeground(new java.awt.Color(0, 0, 0));
        txtTaIC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaIC.setSelectionColor(new java.awt.Color(255, 255, 51));

        txtTaGender.setEditable(false);
        txtTaGender.setBackground(new java.awt.Color(204, 204, 204));
        txtTaGender.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTaGender.setForeground(new java.awt.Color(0, 0, 0));
        txtTaGender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaGender.setSelectionColor(new java.awt.Color(255, 255, 51));

        txtTaName.setEditable(false);
        txtTaName.setBackground(new java.awt.Color(204, 204, 204));
        txtTaName.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTaName.setForeground(new java.awt.Color(0, 0, 0));
        txtTaName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaName.setSelectionColor(new java.awt.Color(255, 255, 51));

        btnTaMark.setBackground(new java.awt.Color(102, 255, 102));
        btnTaMark.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnTaMark.setForeground(new java.awt.Color(0, 0, 0));
        btnTaMark.setText("Mark As Vaccinated");
        btnTaMark.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTaMark.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTaMark.setOpaque(true);
        btnTaMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaMarkActionPerformed(evt);
            }
        });

        jLabel64.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 0, 0));
        jLabel64.setText("Appointment Info.");

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Centre:");

        txtTaCentre.setEditable(false);
        txtTaCentre.setBackground(new java.awt.Color(204, 204, 204));
        txtTaCentre.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTaCentre.setForeground(new java.awt.Color(0, 0, 0));
        txtTaCentre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaCentre.setSelectionColor(new java.awt.Color(255, 255, 51));

        txtTaAppCode.setEditable(false);
        txtTaAppCode.setBackground(new java.awt.Color(204, 204, 204));
        txtTaAppCode.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTaAppCode.setForeground(new java.awt.Color(0, 0, 0));
        txtTaAppCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaAppCode.setSelectionColor(new java.awt.Color(255, 255, 51));

        calTaDob.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Date of Birth:");

        jLabel65.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 0, 0));
        jLabel65.setText("Registrant Info.");

        jLabel66.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 0, 0));
        jLabel66.setText("Vaccination Info.");

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Status:");

        txtTaStatus.setEditable(false);
        txtTaStatus.setBackground(new java.awt.Color(204, 204, 204));
        txtTaStatus.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTaStatus.setForeground(new java.awt.Color(0, 0, 0));
        txtTaStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaStatus.setSelectionColor(new java.awt.Color(255, 255, 51));

        calTaDate.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Vaccine & Dose");

        txtTaDose.setEditable(false);
        txtTaDose.setBackground(new java.awt.Color(204, 204, 204));
        txtTaDose.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTaDose.setForeground(new java.awt.Color(0, 0, 0));
        txtTaDose.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaDose.setSelectionColor(new java.awt.Color(255, 255, 51));

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Remarks");

        txtTaRemarks.setEditable(false);
        txtTaRemarks.setBackground(new java.awt.Color(204, 204, 204));
        txtTaRemarks.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTaRemarks.setForeground(new java.awt.Color(0, 0, 0));
        txtTaRemarks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaRemarks.setSelectionColor(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(txtTaAppCode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtTaVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTaDose, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                    .addComponent(txtTaCentre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calTaDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTaStatus, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtTaIC, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTaNat))
                                    .addComponent(calTaDob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTaGender, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTaName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTaRemarks)))
                            .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTaMark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaAppCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel65)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTaName)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTaGender)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calTaDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTaIC)
                        .addComponent(txtTaNat))
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTaStatus))
                .addGap(45, 45, 45)
                .addComponent(jLabel66)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(calTaDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTaCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTaVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaDose, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtTaRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnTaMark, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cboTaVaccine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Vaccines" }));
        cboTaVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTaVaccineActionPerformed(evt);
            }
        });

        cboTaStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Status" }));
        cboTaStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTaStatusActionPerformed(evt);
            }
        });

        cboTaNationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Nationality" }));
        cboTaNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTaNationalityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(txtTaSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTASearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboTaVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTaNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1898, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTASearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaSearch)
                    .addComponent(cboTaVaccine)
                    .addComponent(cboTaNationality)
                    .addComponent(cboTaStatus))
                .addGap(27, 27, 27)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel18);

        jTabbedPane1.addTab("Today's Appointment", jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1341, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editProfile(boolean b) {
        btnAdPSave.setVisible(b);
        btnAdPInfoEdit.setVisible(!b);
        pnlCredential.setVisible(b);

        Color col = b ? Color.WHITE : Color.GRAY;

        for (Component x : pnlCredential.getComponents()) {

            if (x instanceof JTextField) {
                JTextField j = (JTextField) x;
                j.setEnabled(j.isEditable() && b);
                j.setBackground(col);
            } else if (x instanceof JPasswordField) {
                JPasswordField j = (JPasswordField) x;
                j.setEnabled(b);
                j.setText("");
                j.setBackground(col);
            }
        }
    }

    public void StartUp() {
        InitGlobalData();
        InitComboData();
        PopulateUserData();
        InitTableRecords();

    }

    private void InitGlobalData() {
        ArrayList<Object> allAppointments = FileOperation.DeserializeObject(General.appointmentFileName);
        htAppointment = FileOperation.ConvertToHashTable(allAppointments);

    }

    private void InitComboData() {
        //---Profile Tab---
        //Init Gender ComboBox
        General.GenderString().forEach(d -> cboAdPGender.addItem(d));

        //---Vaccination Appointment---
        //Init Vaccine Types 
        ArrayList<Object> allVaccines = FileOperation.DeserializeObject(General.vaccineFileName);
        for (Object x : allVaccines) {
            Vaccine v = (Vaccine) x;
            cboTaVaccine.addItem(v.getVacCode() + " - " + v.getName());
        }

        //Init Nationality 
        General.Nationalities().forEach(d -> cboTaNationality.addItem(d));

        for (VaccinationStatus x : VaccinationStatus.values()) {
            cboTaStatus.addItem(String.valueOf(x));
        }

    }

    private void PopulateUserData() {
        lblWbUsername.setText(currentUser.getFirst_Name());

        //---Profile Tab---
        txtAdPFullName.setText(currentUser.getFullName());

        String Gender = currentUser.getGender() == General.GenderMale ? General.GenderMaleString : General.GenderFemaleString;
        cboAdPGender.setSelectedItem(Gender);

        jDob.setCalendar(currentUser.Dob.getCal());

        txtAdPNo.setText(currentUser.getContact());
        txtPEmail.setText(currentUser.getEmail());
        txtAdPUser.setText(currentUser.Username);

        txtAdPRole.setText(General.PersonnelRoleDoctor);
        calAdPHiredDate.setCalendar(currentUser.HiredDate.getCal());
        txtAdPVacCentre.setText(currentUser.VacCentre.getVacCode() + " - " + currentUser.VacCentre.getName());

        txtPNewPw.setText("");
        txtPCfmPw.setText("");

    }

    private void InitTableRecords() {
        //----------Today Appointment----------
        DefaultTableModel dtmTA = (DefaultTableModel) tblTA.getModel();
        dtmTA.setRowCount(0);
        int i = 0;

        for (Object x : htAppointment.values()) {
            Appointment a = (Appointment) x;

            if (!(a.getStatus() == AppointmentStatus.Accepted)) {
                continue;
            }
            
            if(!a.Location.getVacCode().equals(currentUser.VacCentre.getVacCode())){
                continue;
            }

            MyDateTime today = new MyDateTime();
            MyDateTime tomorrow = today;
            tomorrow.getCal().add(Calendar.DATE, 1);
            if (!(a.VaccinationDate.getCal().after(today)) && a.VaccinationDate.getCal().before(tomorrow)) {
                continue;
            }

            String IcPassport = "";
            if (a.Ppl.getIsCitizen()) {
                Citizen c = (Citizen) a.Ppl;
                IcPassport = c.getIcNo() + " (" + General.NationalityCitizen + ")";
            } else {
                NonCitizen c = (NonCitizen) a.Ppl;
                IcPassport = c.getPassport() + " (" + General.NationalityNonCitizen + ")";
            }

            Object[] dtmObj = new Object[]{
                ++i,
                a.getCode(),
                a.Ppl.getFullName() + " (" + a.Ppl.Username + ")",
                IcPassport,
                a.Vacc.GetCodeName(),
                a.getStatus()
            };

            dtmTA.addRow(dtmObj);

        }

        tblTA.setModel(dtmTA);

    }

    public void setCurrentUser(Doctor user) {
        this.currentUser = user;
        InitGlobalData();
    }


    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tblTAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTAMouseClicked
        DefaultTableModel Tmode = (DefaultTableModel) tblTA.getModel();

        //Display data into text field when the specific row is selected
        String code = Tmode.getValueAt(tblTA.getSelectedRow(), 1).toString();
        txtTaAppCode.setText(code);

        //Retrieve the data
        Appointment data = (Appointment) htAppointment.get(code);

        txtTaName.setText(data.Ppl.getFullName());

        String Gender = data.Ppl.getGender() == General.GenderMale ? General.GenderMaleString : General.GenderFemaleString;
        txtTaGender.setText(Gender);

        calTaDob.setCalendar(data.getRegisterDate().getCal());

        if (data.Ppl.getIsCitizen()) {
            Citizen c = (Citizen) data.Ppl;
            txtTaIC.setText(c.getIcNo());
            txtTaNat.setText(General.NationalityCitizen);
        } else {
            NonCitizen c = (NonCitizen) data.Ppl;
            txtTaIC.setText(c.getPassport());
            txtTaNat.setText(General.NationalityCitizen);
        }

        txtTaStatus.setText(String.valueOf(data.getStatus()));

        calTaDate.setCalendar(data.VaccinationDate.getCal());
        txtTaCentre.setText(data.Location.GetCodeName());
        txtTaVaccine.setText(data.Vacc.GetCodeName());

        //Check old dose
        txtTaDose.setText(String.valueOf(data.CheckDoseFromAppointment()));
        txtTaRemarks.setText(data.getRemarks());

        btnTaMark.setEnabled(data.getStatus() == AppointmentStatus.Accepted);
    }//GEN-LAST:event_tblTAMouseClicked

    private void btnTASearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTASearchActionPerformed
        String search = (!txtTaSearch.getText().isBlank() ? txtTaSearch.getText() : "").trim().toLowerCase();

        Class nat = null;
        if (cboTaNationality.getSelectedIndex() > 0) {
            switch (String.valueOf(cboTaNationality.getSelectedItem())) {
                case General.NationalityCitizen:
                    nat = Citizen.class;
                    break;
                case General.NationalityNonCitizen:
                    nat = NonCitizen.class;
                    break;
                default:
                    nat = null;
            }
        }

        VaccinationStatus status = (cboTaStatus.getSelectedIndex() > 0) ? VaccinationStatus.valueOf(String.valueOf(cboTaStatus.getSelectedItem())) : null;
        String vacCode = (cboTaVaccine.getSelectedIndex() > 0) ? String.valueOf(cboTaVaccine.getSelectedItem()).split(" - ")[0] : "";

        Vaccine vac = null;
        if (vacCode.isBlank()) {
            FileOperation fo = new FileOperation(vacCode, General.vaccineFileName);
            fo.ReadFile();
            vac = (Vaccine) fo.getReadResult();
        }
        TASearch(search, vac, status, nat);
    }//GEN-LAST:event_btnTASearchActionPerformed

    private void TASearch(String search, Vaccine vac, VaccinationStatus status, Class nat) {
        int i = 0;

        DefaultTableModel dtm = (DefaultTableModel) tblTA.getModel();
        dtm.setRowCount(0);

        for (Object x : htAppointment.values()) {
            Appointment a = (Appointment) x;

            if (!a.getStatus().equals(AppointmentStatus.Accepted)) {
                continue;
            }

            if (!a.Location.getVacCode().equals(currentUser.VacCentre.getVacCode())) {
                continue;
            }

            if (vac != null) {
                if (!a.Vacc.getVacCode().equals(vac.getVacCode())) {
                    continue;
                }
            }

            if (status != null) {
                if (!a.Ppl.getVacStatus().equals(status)) {
                    continue;
                }
            }

            //Ppl type
            Class pplClass = a.Ppl.getClass();

            if (nat != null) {
                if (!nat.equals(pplClass)) {
                    continue;
                }
            }

            //Search bar check
            if (pplClass.equals(Citizen.class)) {
                Citizen c = (Citizen) a.Ppl;

                if ((c.getIcNo().toLowerCase().contains(search) || a.getCode().toLowerCase().contains(search) || a.Ppl.Username.toLowerCase().contains(search) || a.Ppl.getFullName().toLowerCase().contains(search))) {
                    Object[] dtmObj = new Object[]{
                        ++i,
                        a.getCode(),
                        a.Ppl.getFullName() + "(" + a.Ppl.Username + ")",
                        c.getIcNo() + "(" + General.NationalityCitizen + ")",
                        a.Vacc != null ? a.Vacc.getVacCode() + " - " + a.Vacc.getName() : "-",
                        a.getStatus()
                    };

                    dtm.addRow(dtmObj);
                }
            } else {
                NonCitizen c = (NonCitizen) a.Ppl;
                if (c.getPassport().toLowerCase().contains(search) || a.getCode().toLowerCase().contains(search) || a.Ppl.Username.toLowerCase().contains(search) || a.Ppl.getFullName().toLowerCase().contains(search)) {
                    Object[] dtmObj = new Object[]{
                        ++i,
                        a.getCode(),
                        a.Ppl.getFullName() + "(" + a.Ppl.Username + ")",
                        c.getPassport() + "(" + General.NationalityNonCitizen + ")",
                        a.Vacc != null ? a.Vacc.getVacCode() + " - " + a.Vacc.getName() : "-",
                        a.getStatus()
                    };

                    dtm.addRow(dtmObj);
                }
            }

        }

        tblTA.setModel(dtm);
    }

    private void btnTaMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaMarkActionPerformed
        String code = txtTaAppCode.getText();

        if (code.isBlank()) {
            General.AlertMsgError("Please select a record!", "Record Required");
            return;
        }

        //Appointment's
        FileOperation fo = new FileOperation(code, General.appointmentFileName);
        fo.ReadFile();
        Appointment data = (Appointment) fo.getReadResult();

        data.setStatus(AppointmentStatus.Completed);
        data.setVaccinatedBy(currentUser);

        int dose = Integer.parseInt(txtTaDose.getText());

        //Modify Stock
        Stock s = new Stock(data.Vacc, dose, data.Location);

        if (s.FindStock()) {
            if (!s.MinusQty(dose, currentUser, "Vaccination - " + data.getCode())) {
                General.AlertMsgError("Not enough stock please inform stockist to add stock!", "Error");
                return;
            }

            if (!s.MinusPendingQty(dose, currentUser, "Vaccination - " + data.getCode())) {
                General.AlertMsgError("Not enough stock, please inform stockist to add stock!", "Error");
                return;
            }

        } else {
            General.AlertMsgError("Out of stock!", "Error");
            return;
        }

        if (!fo.ModifyRecords()) {
            General.AlertMsgError("Failed to mark " + data.Ppl.getFullName() + "(" + data.Ppl.Username + ") as vaccinated. Please try again later!", "Error");
            return;
        }

        if (data.Vacc.getDoseCount() > dose) {
            //Save stock
            FileOperation fo2 = new FileOperation(s.getId(), General.stockFileName);
            fo2.ModifyRecord(s);

            //Create new appointment
            MyDateTime newVacDate = new MyDateTime();
            newVacDate.getCal().add(Calendar.DATE, data.Vacc.getInterval());

            Appointment newApp = new Appointment(data.Ppl, data.getHandledBy(), data.Vacc, data.Location, newVacDate);

            //Update vac status of ppl
            FileOperation foPpl = new FileOperation(data.Ppl.Username, General.userFileName);
            foPpl.ReadFile();
            People ppl = (People) foPpl.getReadResult();
            ppl.setVacStatus(VaccinationStatus.Partially);

            if (!foPpl.ModifyRecord(ppl)) {
                General.AlertMsgError("Failed to update " + data.Ppl.getFullName() + "(" + data.Ppl.Username + ") vaccination status. Please edit manually.", "Error");
                return;
            }

            if (!FileOperation.SerializeObject(General.appointmentFileName, newApp)) {
                General.AlertMsgError("Failed to schedule next apointment for " + data.Ppl.getFullName() + "(" + data.Ppl.Username + "). Please inform patient to self-enroll.", "Error");
                return;
            }

        } else {
            //Update vac status of ppl
            FileOperation foPpl = new FileOperation(data.Ppl.Username, General.userFileName);
            foPpl.ReadFile();
            People ppl = (People) foPpl.getReadResult();
            ppl.setVacStatus(VaccinationStatus.Fully);

            if (!foPpl.ModifyRecord(ppl)) {
                General.AlertMsgError("Failed to update " + data.Ppl.getFullName() + "(" + data.Ppl.Username + ") vaccination status. Please edit manually.", "Error");
                return;
            }
        }

        General.AlertMsgInfo(data.Ppl.getFullName() + "(" + data.Ppl.Username + ") is marked as vaccinated!", "Success");
        InitGlobalData();
        InitTableRecords();

    }//GEN-LAST:event_btnTaMarkActionPerformed

    private void txtPNewPwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPNewPwKeyReleased
        txtPCfmPw.setEnabled(txtPNewPw.getPassword().length > 0);
        txtPCfmPw.setText("");
        lblPwNoMatch.setVisible(txtPCfmPw.isEnabled());
    }//GEN-LAST:event_txtPNewPwKeyReleased

    private void txtPNewPwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPNewPwKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPNewPwKeyTyped

    private void txtPCfmPwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCfmPwKeyReleased
        lblPwNoMatch.setVisible(!String.valueOf(txtPNewPw.getPassword()).equals(String.valueOf(txtPCfmPw.getPassword())));
    }//GEN-LAST:event_txtPCfmPwKeyReleased

    private void btnAdPSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdPSaveActionPerformed
        if (General.AlertQuestionYesNo("Do you want to save your changes?", "Save Confirmation") == 1) {
            return;
        }

        //Check field filled
        if (txtAdPNo.getText().isBlank() || txtPEmail.getText().isBlank()) {
            General.AlertMsgError("All details have to be filled.", "Profile Update Failed!");
            return;
        }
        
        if(!txtPEmail.getText().matches("^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$")){
            General.AlertMsgError("Email format invalid.", "Profile Create Failed!");
            return;
        }

        //Check Pw Any Changes
        if (txtPNewPw.getPassword().length != 0) {
            //Password doesnt match

            if (!String.valueOf(txtPNewPw.getPassword()).equals(String.valueOf(txtPCfmPw.getPassword()))) {
                General.AlertMsgError("New Password doesn't match with Confirm Password.", "Profile Update Failed!");
                return;
            } else {
                currentUser.setPassword(String.valueOf(txtPNewPw.getPassword()));

            }

        }

        String phone = txtAdPNo.getText().trim();
        String email = txtPEmail.getText();

        currentUser.setContact(phone);
        currentUser.setEmail(email);

        FileOperation fo = new FileOperation(currentUser.Username, General.userFileName);
        fo.ReadFile();

        if (fo.ModifyRecord(currentUser)) {
            General.AlertMsgInfo("Profile has been updated.", "Success!");
            editProfile(false);
            InitTableRecords();
        } else {
            General.AlertMsgError("Profile changes were not saved, please try again later.", "Error!");
        }
    }//GEN-LAST:event_btnAdPSaveActionPerformed

    private void btnAdPInfoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdPInfoEditActionPerformed
        editProfile(true);
    }//GEN-LAST:event_btnAdPInfoEditActionPerformed

    private void cboTaVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTaVaccineActionPerformed
        String search = (!txtTaSearch.getText().isBlank() ? txtTaSearch.getText() : "").trim().toLowerCase();

        Class nat = null;
        if (cboTaNationality.getSelectedIndex() > 0) {
            switch (String.valueOf(cboTaNationality.getSelectedItem())) {
                case General.NationalityCitizen:
                    nat = Citizen.class;
                    break;
                case General.NationalityNonCitizen:
                    nat = NonCitizen.class;
                    break;
                default:
                    nat = null;
            }
        }

        VaccinationStatus status = (cboTaStatus.getSelectedIndex() > 0) ? VaccinationStatus.valueOf(String.valueOf(cboTaStatus.getSelectedItem())) : null;
        String vacCode = (cboTaVaccine.getSelectedIndex() > 0) ? String.valueOf(cboTaVaccine.getSelectedItem()).split(" - ")[0] : "";

        Vaccine vac = null;
        if (vacCode.isBlank()) {
            FileOperation fo = new FileOperation(vacCode, General.vaccineFileName);
            fo.ReadFile();
            vac = (Vaccine) fo.getReadResult();
        }
        TASearch(search, vac, status, nat);
    }//GEN-LAST:event_cboTaVaccineActionPerformed

    private void cboTaStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTaStatusActionPerformed
        String search = (!txtTaSearch.getText().isBlank() ? txtTaSearch.getText() : "").trim().toLowerCase();

        Class nat = null;
        if (cboTaNationality.getSelectedIndex() > 0) {
            switch (String.valueOf(cboTaNationality.getSelectedItem())) {
                case General.NationalityCitizen:
                    nat = Citizen.class;
                    break;
                case General.NationalityNonCitizen:
                    nat = NonCitizen.class;
                    break;
                default:
                    nat = null;
            }
        }

        VaccinationStatus status = (cboTaStatus.getSelectedIndex() > 0) ? VaccinationStatus.valueOf(String.valueOf(cboTaStatus.getSelectedItem())) : null;

        String vacCode = (cboTaVaccine.getSelectedIndex() > 0) ? String.valueOf(cboTaVaccine.getSelectedItem()).split(" - ")[0] : "";

        Vaccine vac = null;
        if (vacCode.isBlank()) {
            FileOperation fo = new FileOperation(vacCode, General.vaccineFileName);
            fo.ReadFile();
            vac = (Vaccine) fo.getReadResult();
        }
        TASearch(search, vac, status, nat);
    }//GEN-LAST:event_cboTaStatusActionPerformed

    private void cboTaNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTaNationalityActionPerformed
        String search = (!txtTaSearch.getText().isBlank() ? txtTaSearch.getText() : "").trim().toLowerCase();

        Class nat = null;
        if (cboTaNationality.getSelectedIndex() > 0) {
            switch (String.valueOf(cboTaNationality.getSelectedItem())) {
                case General.NationalityCitizen:
                    nat = Citizen.class;
                    break;
                case General.NationalityNonCitizen:
                    nat = NonCitizen.class;
                    break;
                default:
                    nat = null;
            }
        }

        VaccinationStatus status = (cboTaStatus.getSelectedIndex() > 0) ? VaccinationStatus.valueOf(String.valueOf(cboTaStatus.getSelectedItem())) : null;
        String vacCode = (cboTaVaccine.getSelectedIndex() > 0) ? String.valueOf(cboTaVaccine.getSelectedItem()).split(" - ")[0] : "";

        Vaccine vac = null;
        if (vacCode.isBlank()) {
            FileOperation fo = new FileOperation(vacCode, General.vaccineFileName);
            fo.ReadFile();
            vac = (Vaccine) fo.getReadResult();
        }
        TASearch(search, vac, status, nat);
    }//GEN-LAST:event_cboTaNationalityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorLoadingPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorLoadingPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorLoadingPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorLoadingPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorLoadingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdPInfoEdit;
    private javax.swing.JButton btnAdPSave;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTASearch;
    private javax.swing.JButton btnTaMark;
    private com.toedter.calendar.JDateChooser calAdPHiredDate;
    private com.toedter.calendar.JDateChooser calTaDate;
    private com.toedter.calendar.JDateChooser calTaDob;
    private javax.swing.JComboBox<String> cboAdPGender;
    private javax.swing.JComboBox<String> cboTaNationality;
    private javax.swing.JComboBox<String> cboTaStatus;
    private javax.swing.JComboBox<String> cboTaVaccine;
    private com.toedter.calendar.JDateChooser jDob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblPwNoMatch;
    private javax.swing.JLabel lblVSName2;
    private javax.swing.JLabel lblVSName3;
    private javax.swing.JLabel lblWbUsername;
    private javax.swing.JPanel pnlCredential;
    private javax.swing.JTable tblTA;
    private javax.swing.JTextField txtAdPFullName;
    private javax.swing.JTextField txtAdPNo;
    private javax.swing.JTextField txtAdPRole;
    private javax.swing.JTextField txtAdPUser;
    private javax.swing.JTextField txtAdPVacCentre;
    private javax.swing.JPasswordField txtPCfmPw;
    private javax.swing.JTextField txtPEmail;
    private javax.swing.JPasswordField txtPNewPw;
    private javax.swing.JTextField txtTaAppCode;
    private javax.swing.JTextField txtTaCentre;
    private javax.swing.JTextField txtTaDose;
    private javax.swing.JTextField txtTaGender;
    private javax.swing.JTextField txtTaIC;
    private javax.swing.JTextField txtTaName;
    private javax.swing.JTextField txtTaNat;
    private javax.swing.JTextField txtTaRemarks;
    private javax.swing.JTextField txtTaSearch;
    private javax.swing.JTextField txtTaStatus;
    private javax.swing.JTextField txtTaVaccine;
    // End of variables declaration//GEN-END:variables
}
